export const words = [
    "apple", "banana", "chair", "table", "pencil", "book", "window", "door", "car", "tree",
    "river", "ocean", "cloud", "sun", "moon", "star", "house", "school", "garden", "street",
    "flower", "grass", "bird", "dog", "cat", "fish", "ball", "game", "hat", "shoes", "shirt",
    "pants", "jacket", "computer", "phone", "lamp", "bed", "couch", "mirror", "clock", "picture",
    "run", "walk", "jump", "talk", "write", "read", "listen", "watch", "eat", "drink",
    "sleep", "wake", "play", "think", "learn", "laugh", "smile", "cry", "work", "help",
    "buy", "sell", "open", "close", "push", "pull", "hold", "drop", "carry", "drive",
    "call", "dance", "sing", "sit", "stand", "shake", "wave", "clap", "paint", "build",
    "big", "small", "fast", "slow", "hot", "cold", "happy", "sad", "easy", "hard",
    "new", "old", "young", "strong", "weak", "light", "dark", "soft", "loud", "quiet",
    "bright", "dull", "clean", "dirty", "funny", "serious", "tall", "short", "wide", "narrow",
    "thick", "thin", "full", "empty", "sweet", "bitter", "kind", "mean", "nice", "rude",
    "quickly", "slowly", "happily", "sadly", "easily", "hardly", "quietly", "loudly", "softly", "strongly",
    "gently", "angrily", "brightly", "darkly", "warmly", "coldly", "clearly", "politely", "rudely", "kindly",
    "safely", "dangerously", "carefully", "recklessly", "excitedly", "nervously", "calmly", "honestly", "bravely", "shyly",
    "freely", "loosely", "tightly", "lightly", "heavily", "firmly", "wildly", "silently", "cheerfully", "gracefully",
    "he", "she", "it", "they", "we", "you", "me", "him", "her", "us",
    "above", "below", "between", "under", "over", "inside", "outside", "beside", "around", "through",
    "before", "after", "during", "since", "until", "with", "without", "against", "about", "among",
    "and", "or", "but", "so", "because", "although", "if", "when", "while", "where",
    "wow", "oops", "hey", "oh", "yay", "ouch", "aha", "hmm", "yikes", "phew",
    "morning", "afternoon", "evening", "night", "yesterday", "today", "tomorrow", "always", "never", "sometimes",
    "north", "south", "east", "west", "summer", "winter", "spring", "autumn", "rain", "snow",
    "thunder", "lightning", "storm", "wind", "breeze", "fog", "ice", "fire", "earth", "sky"
];

const christianVocabulary = [
  // Simple words
  "God", "Jesus", "Bible", "Cross", "Faith", "Church", "Grace", "Hope", "Love", "Sin",
  "Pray", "Amen", "Truth", "Gospel", "Mercy", "Praise", "Saved", "Holy", "Peace", "Christ",
  "Word", "Light", "Glory", "Spirit", "Trust", "Joy", "Worship", "Bless", "Forgive", "Serve",
  "Judge", "Believe", "Savior", "Lord", "Soul", "Hymn", "Saint", "Truthful", "Virtue", "Devout",
  "Baptism", "Scripture", "Covenant", "Redemption", "Salvation", "Disciple", "Apostle", "Prophet", "Righteous",
  "Confession", "Communion", "Deliverance", "Fellowship", "Ministry", "Anointed", "Justified", "Repentance",
  "Testament", "Sanctify", "Resurrection", "Exaltation", "Manifest", "Obedience", "Almighty", "Reverence",
  "Intercede", "Supplication", "Sacrament", "Consecrate", "Pardon", "Omnipotent", "Omniscient", "Shepherd",
  "Transcend", "Beatitudes", "Martyrdom", "Absolution", "Ecclesia", "Messianic", "Pilgrimage", "Sacrosanct",
  "Adoration", "Pentecost", "Regeneration", "Mortification", "Doctrine", "Charismatic", "Exegesis", "Hermeneutics",  "Justification", "Sanctification", "Eschatology", "Dispensation", "Predestination", "Propitiation", "Imputation",
  "Atonement", "Theophany", "Incarnation", "Transubstantiation", "Hypostatic", "Trinitarian", "Soteriology",
  "Ecclesiology", "Christology", "Pneumatology", "Canonization", "Apologetics", "Epistemology", "Omnipresence",
  "Omnibenevolence",
]

const footballWords = [
    "goal", "assist", "penalty", "tackle", "dribble", "pass", "shoot", "offside", "header", "foul",
    "cornerKick", "goalKick", "freeKick", "throwIn", "yellowCard", "redCard", "referee", "whistle",
    "substitution", "extraTime", "stoppageTime", "kickoff", "crossbar", "goalpost", "formation",
    "defender", "midfielder", "forward", "striker", "goalkeeper", "captain", "coach", "manager",
    "stadium", "pitch", "matchday", "counterattack", "possession", "setPiece", "throughBall",
    "volley", "halfTime", "fullTime", "sprint", "injuryTime", "nutmeg", "chipShot", "longBall",
    "pressing", "zonalMarking", "manMarking", "sweeper", "wingBack", "boxToBox", "playmaker",
    "falseNine", "deepLyingPlaymaker", "targetMan", "overlappingRun", "counterPress", "highPress",
    "lowBlock", "midBlock", "gegenPressing", "totalFootball", "sweeperKeeper", "ballPlayingDefender",
    "invertedWinger", "advancedPlaymaker", "defensiveMidfielder", "shadowStriker", "trequartista",
    "regista", "libero", "poacher", "insideForward", "anchorMan", "holdingMidfielder", "maestro",
    "worldCup", "championsLeague", "euros", "copaAmerica", "afcon", "clubWorldCup", "ballonDor",
    "goldenBoot", "puskasAward", "fifaBest", "scudetto", "premierLeague", "laLiga", "bundesliga",
    "serieA", "ligue1", "eredivisie", "carabaoCup", "faCup", "communityShield", "superCup",
    "nationsLeague", "copaDelRey", "dfbPokal", "coppaItalia", "uefaSuperCup", "europaLeague",
    "conferenceLeague", "relegation", "promotion", "playoffs", "derbyMatch", "elClasico",
    "manchesterDerby", "northLondonDerby", "merseysideDerby", "madridDerby",
    "pele", "maradona", "cruyff", "beckham", "zidane", "ronaldinho", "messi", "ronaldo",
    "neymar", "mbappe", "haaland", "lewandowski", "salah", "modric", "xavi", "iniesta",
    "suarez", "benzema", "rooney", "henry", "batistuta", "vanBasten", "shevchenko", "rivaldo",
    "figo", "giggs", "cantona", "lampard", "gerrard", "terry", "puyol", "maldini", "baggio",
    "pirlo", "kaka", "ramos", "casillas", "buffon", "schmeichel", "yashin", "eusebio",
    "diStefano", "matthaus", "beckenbauer", "klinsmann", "klose", "stoichkov", "berkamp",
    "weah", "totti", "delPiero", "hagi", "zico", "socrates", "drogba", "eto", "kanu", "jayJay",
    "mikel", "osimhen", "georgeBest", "charlton", "bobbyMoore", "cristante", "goretzka",
    "kimmich", "griezmann", "deBruyne", "pique", "busquets", "vidic", "ferdinand", "alaba",
    "vanDijk", "robben", "ribery", "sneijder", "deLigt", "davies", "chiesa", "lukaku", "donnarumma",
    "pogba", "kante", "varane", "zlatan", "alexanderArnold", "robertson", "mahrez", "sonHeungMin",
    "rashford", "foden", "bellingham", "saka", "odegaard", "martinez", "alisson", "ederson",
    "courtois", "neuer", "modeste", "gravenberch", "sancho", "greenwood", "maddison"
]

export const medicalWords = [
    "anemia", "asthma", "biopsy", "bronchi", "cartilage", "diagnosis", "disease", "enzyme", "fatigue", "fracture",
    "gallbladder", "glucose", "hormone", "immune", "infection", "inflammation", "insulin", "joint", "kidney", "ligament",
    "liver", "lymphatic", "migraine", "muscle", "nausea", "neuron", "organ", "pancreas", "pathogen", "pharmacy",
    "physician", "plasma", "pulse", "rehydration", "respiration", "sutures", "tendon", "thermometer", "tonsil", "toxin",
    "abdomen", "absorption", "allergy", "amnesia", "anatomy", "anesthetic", "antibody", "antiseptic", "artery", "bacteria",
    "cardiology", "catheter", "cellular", "circulatory", "coagulation", "congenital", "contagious", "cranial", "dermatology",
    "diagnostic", "digestive", "dysfunction", "electrolyte", "embryology", "endocrine", "epidemic", "epidermis", "fibrosis",
    "gastroenterology", "genetics", "geriatrics", "hematology", "hemoglobin", "homeostasis", "hydrotherapy", "hypertension",
    "hypotension", "incision", "inoculation", "intubation", "intravenous", "ischemia", "laceration", "laparoscopy", "larynx",
    "leukocyte", "lumbar", "malignant", "metabolism", "morphology", "neurology", "nucleus", "obstetrics", "oncology", "ophthalmology",
    "orthopedic", "osteopathy", "otolaryngology", "oxygenation", "palliative", "paralysis", "pathology", "pediatrics",
    "phlebotomy", "physiology", "prognosis", "psychiatry", "radiology", "receptor", "rehabilitation", "reproductive",
    "respiratory", "rheumatology", "scoliosis", "sedation", "skeletal", "somatic", "spinalcord", "stethoscope", "subcutaneous",
    "sublingual", "symptomatology", "tachycardia", "thoracic", "toxicology", "tracheotomy", "transfusion", "triage",
    "ultrasound", "urology", "vascular", "virology", "xenotransplantation", "zygomatic", "zygomorphic", "zoonotic", "neurotransmitter",
    "amniotic", "angioplasty", "anticoagulant", "antihistamine", "bronchoscopy", "chiropractic", "cholecystectomy",
    "cytology", "dermatitis", "dysplasia", "endoscope", "eosinophil", "epidemiology", "erythrocyte", "fibrillation",
    "gastrectomy", "glomerulus", "hemangioma", "hemorrhoid", "hepatitis", "hyperplasia", "hypertrophy", "laparotomy",
    "laryngitis", "lymphocyte", "macrophage", "melanocyte", "microbiology", "mitochondria", "mononucleosis",
    "myocardium", "nephrology", "neuromuscular", "neurophysiology", "nucleoplasm", "oncogene", "ophthalmoscope",
    "otitis", "pancreatitis", "pericardium", "peritoneum", "pharmacology", "phlebitis", "pneumothorax", "polydipsia",
    "polyuria", "postoperative", "pulmonology", "retroperitoneal", "serology", "sinusitis", "sphygmomanometer",
    "thrombocytopenia", "trigeminal", "vasodilation", "vertebrae", "xiphoid", "zygomaticbone", "zoonosis", "lymphadenopathy"  
]